In [12]:
import numpy as np

arr1 = np.arange(9).reshape((3, 3))
print(arr1)
arr2 = np.arange(0, 18, 2).reshape((3, 3))
print(arr2)
print(arr1 + arr2)
print(arr1 - arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
[[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]
