In [2]:
import numpy as np


a = np.array([[1, -1], [0, 3], [0, -2], [0, -2]])
print(a)
b = np.array([[1,2,3], [0, 3, 6]])


print(np.dot(a, b))
print(np.dot(b, a))


[[ 1 -1]
 [ 0  3]
 [ 0 -2]
 [ 0 -2]]
[[  1  -1  -3]
 [  0   9  18]
 [  0  -6 -12]
 [  0  -6 -12]]


ValueError: shapes (2,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)